name: Run LWC Unit Tests

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - 'feature/*'
  workflow_dispatch:

jobs:
  report-lwc-code-coverage:
    name: Report LWC Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
      - name: Report LWC Code Coverage
        run: |
          LWC_JEST_VERSION="$(cat package.json | jq --raw-output '.devDependencies ."@salesforce/sfdx-lwc-jest"')"
          npm install @salesforce/sfdx-lwc-jest@$LWC_JEST_VERSION --save-dev
          npm run test:unit:coverage
      - name: Upload code coverage for LWC to Codecov.io
        uses: codecov/codecov-action@v2.0.2
        with:
          flags: LWC
          token: ${{ secrets.CODECOV_TOKEN }}
