name: Run LWC Unit Tests

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - 'feature/*'
  workflow_dispatch:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install lwc-jest
      run: npm install @salesforce/sfdx-lwc-jest@0.9.2 --save-dev
    - name: Run Unit Tests
      run: npm run test:unit
